apiVersion: v1
kind: ServiceAccount
metadata:
  name: general-serviceaccount
  labels:
    account: general-module-service
                                                                                                                                                                                                 